CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC        
C                                                                               
      SEGMENT MVECTD
          REAL*8 VECTBB(INC)
      ENDSEGMENT
      POINTEUR MVECT1.MVECTD,MVECT2.MVECTD,MVECT3.MVECTD
C
**    SEGMENT/MVECTD/(VECTBB(INC)*D),MVECT1.MVECTD,MVECT2.MVECTD,
**   1 MVECT3.MVECTD
C                                                                               
C     OBJET DE TYPE 'VECT''DOUB'                                                
C     LISTE DE REELS DOUBLE PRECISION                                           
C                                                                               
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC        
